PunktDe:
  Analytics:
    elasticsearch:
      server:
        host: elasticsearch
        port: 9200
        scheme: http
        user: elastic
        pass: '%env:ELASTIC_PASSWORD%'
      indexConfiguration: []

    kibana:
      server:
        host: kibana
        port: 5601
        scheme: http
        user: elastic
        pass: '%env:ELASTIC_PASSWORD%'

    internalCustomerIds: [15231]

#     example config for nextcloud
#     nextcloud:
#      example:
#        baseUri: 'https://nextcloud.url/remote.php/webdav/'
#        pathPrefix: '/remote.php/webdav'
#        userName: 'username'
#        password: 'password'
#        authType: 1
#        sourcePath: '/path/to/files'
#        temporaryImportDirectoryName: 'example'
